# Generated by Django 5.2.17 on 2026-09-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='diagnostico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='clinica.mascota'),
        ),
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='tratamiento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clinica.propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
